export const SAVINGS_EVENTS = {
  CREATE_SAVINGS: 'CREATE_SAVINGS',
  UPDATE_SAVINGS: 'UPDATE_SAVINGS',
  GET_ALL_SAVINGS: 'GET_ALL_SAVINGS',
  GET_SAVINGS_BY_ID: 'GET_SAVINGS_BY_ID',
  DELETE_SAVINGS: 'DELETE_SAVINGS',
};