export const INSIGHTS_EVENT = {
  GET_TOTAL_INCOME: 'GET_TOTAL_INCOME',
  GET_TOTAL_EXPENSE: 'GET_TOTAL_EXPENSE',
  GET_MONTHLY_SPENDING: 'GET_MONTHLY_SPENDING',
  GET_TOTAL_SPEND_BY_CATEGORY: 'GET_TOTAL_SPEND_BY_CATEGORY',
  GET_TOP_EXPENSES: 'GET_TOP_EXPENSES',
  GET_DAILY_SPENDING: 'GET_DAILY_SPENDING'
}