export const BUDGET_EVENTS = {
  CREATE_BUDGET: 'CREATE_BUDGET',
  UPDATE_BUDGET: 'UPDATE_BUDGET',
  DELETE_BUDGET: 'DELETE_BUDGET',
  GET_BUDGETS: 'GET_BUDGETS',
  GET_BUDGET_BY_ID: 'GET_BUDGET_BY_ID',
}
