export const BUDGET_ITEM_EVENTS = {
  GET_ALL_BUDGET_ITEMS: 'GET_ALL_BUDGET_ITEMS',
  GET_BUDGET_ITEM_BY_ID: 'GET_BUDGET_ITEM_BY_ID',
  CREATE_BUDGET_ITEM: 'CREATE_BUDGET_ITEM',
  UPDATE_BUDGET_ITEM: 'UPDATE_BUDGET_ITEM',
  DELETE_BUDGET_ITEM: 'DELETE_BUDGET_ITEM',
}