export const EXPENSE_EVENTS = {
  CREATE_EXPENSE: 'CREATE_EXPENSE',
  GET_EXPENSES: 'GET_EXPENSES',
  UPDATE_EXPENSE: 'UPDATE_EXPENSE',
  DELETE_EXPENSE: 'DELETE_EXPENSE',
  GET_CATEGORIES: 'GET_CATEGORIES',
  GET_MORE_EXPENSES: 'GET_MORE_EXPENSES'
};